# Generated by Django 4.2 on 2024-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmtitle', models.CharField(max_length=60)),
                ('filmgenre', models.CharField(max_length=30)),
                ('filmdirector', models.CharField(max_length=60)),
                ('filmpublicationyear', models.IntegerField()),
                ('synopsisofthefilm', models.TextField()),
            ],
        ),
    ]
